### ISSUE TITLE
jiti cli support

### ISSUE THREAD

**Issue by danielroe** [nuxt-contrib/jiti#14]
would be nice to be able to run a node script with `jiti ./script/index.ts` ...

**Comment by pi0** [comment]
It is supported already there :D Would be nice if we somehow support require hook (`node -r jiti`) with pirates

**Comment by pi0** [comment]
@Atinux esno can be compared `npx jiti` (it leverages esbuild register support to implement standalone cli)

Jiti is mainly meant to be a disappearing transpile layer means it only transpiles when needed (esm syntax detected and no native support or file is typescript). Also bringing features like transpile cache.
