### ISSUE TITLE
transpile import.meta.url

### ISSUE THREAD

**Issue by FloEdelmann** [nuxt-contrib/jiti#21]
I have set `"type": "module"` in `package.json`.

I use [`import.meta.url`](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_import_meta) in `nuxt.config.js` and in another ES module that is referenced from `nuxt.config.js`. That other module is also called by Node.js directly, so I can't just use `__filename` or `__dirname` instead.

I suggest transpiling `import.meta.url` to `'file://' + __filename` in Jiti to support this case.

**Comment by linqFR** [comment]
I do not know what the right solution is, but obviously struggling with commonjs is starting to be a real pain !

Till a version of nuxt deals with that, is there any workaround ? (I wish not to rewrite modules to import)

thanks

**Comment by pi0** [comment]
Hi. jiti@1.6.0 supports `import.meta.url` now. Best way to update for nuxt is recreating `yarn.lock`/`package.lock.json` file

@linqFR You can set `createRequire` inside `nuxt.config` to `native` if for any reason but i don't recommand that. Please report any other issues encountered to nuxt repository so we can address :)
