### ISSUE TITLE
allow disabling cache via process.env

### ISSUE THREAD

**Issue by danielroe** [nuxt-contrib/jiti#8]
some environments, like Vercel, will throw an error and abort if fs access to `.cache` is detected - and we may not have control of the jiti call if used in dependencies

**Comment by pi0** [comment]
Actually we are already writing to node_modules/.cache for nuxt. Do you have a log to check?

**Comment by danielroe** [comment]
Yes - check out https://vercel.com/danielroe/jiti-tests/3t01ahmk1 - you may need to trigger the error by:
```bash
curl https://jiti-tests-3t01ahmk1.vercel.app/api/js/csrf
```

**Comment by pi0** [comment]
Dammit! It is in production runtime... 

Actually only reason of using `node_modules/.cache` is ability to debug easier (otherwise we could use os.tempdir())

**Comment by pi0** [comment]
Should be addressed in 0.1.16: https://github.com/nuxt-contrib/jiti/blob/master/CHANGELOG.md#0116-2020-11-23
